export interface Workorder {
  workOrderNo: string
  workOrderId: string
  workOrderUrlId: string
  projectProgress: number
  title: string
  description: any
  jobStatus: string
  materialStatus: string
  commissioningPackageNo: string
  commissioningPackageId: string
  facility: string
  commissioningPackageUrlId: string
  discipline: string
  plannedCompletionDate: string
  actualCompletionDate: string
  workOrderUrl: string
  estimatedManHours: number
  remainingManHours: number
  workBreakdownStructure: string
  responsible: string
}

export interface Punch {
  formTypeUrl: string
  workorderUrl: string
  tagUrl: string
  commissioningPackageUrl: string
  mechanicalCompletionPackageUrl: string
  punchUrl: string
  projectDescription: string
  facility: string
  project: string
  punchItemNo: string
  checklistId: string
  checklistUrlId: string
  description: string
  category: string
  raisedBy: string
  clearedBy: string
  dueDate: any
  sorting: string
  type: string
  priority: string
  priority1: string
  priority2: string
  priority3: string
  status: string
  isOpen: boolean
  hasWO: boolean
  isOverdue: boolean
  estimate: any
  workOrderNo: string
  workOrderId: any
  originalWorkOrderNo: string
  softwareChangeRecordNo: string
  documentNo: string
  externalItemNo: string
  materialRequired: boolean
  materialEstimatedTimeOfArrival: any
  externalMaterialNo: string
  clearedAtDate: any
  rejectedAtDate: any
  verifiedAtDate: any
  createdDate: string
  formularGroup: string
  formularType: string
  formularDiscipline: string
  tagId: string
  tagUrlId: string
  tagNo: string
  discipline: string
  disciplineDescription: string
  responsible: string
  callOffNo: string
  packageNo: string
  commissioningPackageNo: string
  tagArea: string
  commissioningPackageId: string
  commissioningPackageUrlId: string
  identifier: string
  commissioningPackageArea: string
  system: string
  mechanicalCompletionPackageNo: string
  mechanicalCompletionPackageId: string
  mechanicalCompletionPackageUrlId: string
  mechanicalCompletionStatus: string
  handoverPlan: string
  m03PlannedForecastDate: string
  rfcPlannedForecastDate: string
  rfoPlannedForecastDate: string
  punchId: string
  rfcPlannedDate: string
  rfoPlannedDate: string
}
