name: 'Turbo Changed'
description: 'A Github Action making it easy to check if a local workspace changed using Turborepo.'
author: 'Gustav-Eikaas'
inputs:
  turbo-command:
    required: true
    description: 'Branch or commit to diff against (defaults to main)'
  working-directory:
    required: false
    description: 'Defaults to ./'
outputs:
  changed:
    description: 'True if the workspace changed, otherwise false.'

runs:
  using: 'node16'
  main: 'github-action/script/main.js'
