packages:
  - 'libs/**'
  - 'libs/workspace/*'
  - 'apps/*'
  - 'reports/*'
  - 'portal/*'
  - 'fusion-portal/**'
  - 'cli'
  - 'github-action'

catalog:
  # React ecosystem
  react: ^19.2.3
  react-dom: ^19.2.3
  '@types/react': ^19.2.8
  '@types/react-dom': ^19.2.3
  react-error-boundary: ^6.0.3
  react-virtual: ^2.10.4
  react-sortablejs: ^6.1.4

  # Styling
  styled-components: ^6.3.6
  '@types/styled-components': ^5.1.34
  '@emotion/react': ^11.14.0
  '@emotion/styled': ^11.14.1
  stylis: ^4.3.6

  # Equinor Design System
  '@equinor/eds-core-react': ^2.2.0
  '@equinor/eds-icons': ^1.1.0
  '@equinor/eds-tokens': ^2.1.1

  # Equinor Fusion Framework
  '@equinor/fusion-framework-cli': ^13.0.0
  '@equinor/fusion-framework-module': ^5.0.5
  '@equinor/fusion-framework-module-ag-grid': ^34.4.0
  '@equinor/fusion-framework-module-event': ^4.4.0
  '@equinor/fusion-framework-module-http': ^7.0.5
  '@equinor/fusion-framework-module-msal': ^6.0.4
  '@equinor/fusion-framework-react': ^7.4.19
  '@equinor/fusion-framework-react-ag-grid': ^34.4.0
  '@equinor/fusion-framework-react-app': ^8.2.0
  '@equinor/fusion-framework-react-module-bookmark': ^5.0.1
  '@equinor/fusion-framework-react-module-context': ^6.2.33
  '@equinor/fusion-framework-react-module-http': ^10.0.0
  '@equinor/fusion-observable': ^8.5.7
  '@equinor/fusion-react-person': ^1.0.0
  '@equinor/workspace-sidesheet': ^0.1.6

  # Build tools
  typescript: ^5.9.3
  tsup: ^8.5.1
  vite: ^7.3.1
  '@vitejs/plugin-react': ^5.1.2
  turbo: ^2.7.4
  tsx: ^4.21.0
  ts-node: ^10.9.2
  vite-plugin-environment: ^1.1.3
  vite-plugin-eslint: ^1.8.1
  vite-tsconfig-paths: ^6.0.4
  rollup-plugin-inject-process-env: ^1.3.1
  cross-env: ^10.1.0

  # NX
  '@nx/devkit': ^22.3.3
  '@nx/js': ^22.3.3
  '@nx/vite': ^22.3.3
  '@nx/eslint': ^22.3.3
  nx: ^22.3.3

  # SWC
  '@swc-node/register': ^1.11.1
  '@swc/core': ^1.15.8
  '@swc/helpers': ^0.5.18

  # Data fetching
  '@tanstack/react-query': ^5.90.17
  '@tanstack/react-query-devtools': ^5.90.17
  '@tanstack/react-virtual': ^3.13.18
  odata-query: ^8.0.7

  # Microsoft
  '@microsoft/applicationinsights-web': ^3.3.11
  '@microsoft/applicationinsights-core-js': ^3.3.11

  # Testing
  '@types/jest': ^30.0.0
  vitest: ^4.0.17
  '@testing-library/jest-dom': ^6.9.1
  '@testing-library/react': ^16.3.1
  '@testing-library/react-hooks': ^8.0.1

  # Utilities
  luxon: ^3.7.2
  '@types/luxon': ^3.7.1
  sortablejs: ^1.15.6
  '@types/sortablejs': ^1.15.8
  zustand: ^5.0.10
  re-resizable: ^6.11.2
  markdown-to-jsx: ^9.5.7
  date-fns: ^4.1.0
  core-js: ^3.47.0
  rimraf: ^6.0.1
  rxjs: ^7.8.2
  '@types/html-escaper': ^3.0.4
  '@types/node': ^24.2.0

  # Remirror (markdown editor)
  remirror: ^3.0.3
  '@remirror/pm': ^3.0.1
  '@remirror/react': ^3.0.3
  '@remirror/react-editors': ^2.0.3
  '@remirror/react-ui': ^1.0.3
  '@remirror/styles': ^3.0.0
  '@remirror/theme': ^3.0.0

  # 3D/Model Viewer
  '@cognite/reveal': ^4.29.0
  '@cognite/sdk': ^10.5.0
  '@equinor/echo-3d-viewer': ^0.0.4
  three: ^0.182.0
  '@types/three': ^0.182.0
  throttle-typescript: ^1.1.0

  # Power BI
  powerbi-client: ^2.23.9
  powerbi-client-react: ^2.0.0

  # Eslint
  eslint-plugin-import: ^2.32.0
  eslint-plugin-jsx-a11y: ^6.10.2
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-tsdoc: ^0.4.0

  # Astro (docs)
  '@astrojs/react': ^4.4.2
  astro: ^5.16.9

  # GitHub Action
  '@actions/core': ^1.11.1
  '@actions/github': ^6.0.1
  adm-zip: ^0.5.16
  commander: ^14.0.2
  markdown-table: ^3.0.4
