packages:
  - 'libs/**'
  - 'libs/workspace/*'
  - 'apps/*'
  - 'reports/*'
  - 'portal/*'
  - 'fusion-portal/**'
  - 'cli'
  - 'github-action'

catalog:
  # React ecosystem
  react: ^19.1.1
  react-dom: ^19.1.1
  '@types/react': ^19.1.9
  '@types/react-dom': ^19.1.7
  react-error-boundary: ^6.0.0
  react-virtual: ^2.10.4
  react-sortablejs: ^6.1.4

  # Styling
  styled-components: ^6.1.19
  '@types/styled-components': ^5.1.34
  '@emotion/react': ^11.14.0
  '@emotion/styled': ^11.14.1
  stylis: ^4.3.6

  # Equinor Design System
  '@equinor/eds-core-react': ^0.47.0
  '@equinor/eds-icons': ^0.22.0
  '@equinor/eds-tokens': ^0.9.2

  # Equinor Fusion Framework
  '@equinor/fusion-framework-cli': ^10.7.5
  '@equinor/fusion-framework-module': 4.4.2
  '@equinor/fusion-framework-module-ag-grid': 34.0.2
  '@equinor/fusion-framework-module-event': 4.3.6
  '@equinor/fusion-framework-module-http': 6.3.3
  '@equinor/fusion-framework-module-msal': 4.0.7
  '@equinor/fusion-framework-react': 7.4.15
  '@equinor/fusion-framework-react-ag-grid': 33.2.8
  '@equinor/fusion-framework-react-app': 6.2.4
  '@equinor/fusion-framework-react-module-bookmark': 4.0.11
  '@equinor/fusion-framework-react-module-context': 6.2.31
  '@equinor/fusion-framework-react-module-http': 9.0.3
  '@equinor/fusion-observable': 8.5.1
  '@equinor/fusion-react-person': ^0.10.5
  '@equinor/workspace-sidesheet': ^0.1.6

  # Build tools
  typescript: ^5.8.3
  tsup: ^8.5.0
  vite: ^7.0.6
  '@vitejs/plugin-react': ^4.7.0
  turbo: ^2.5.5
  tsx: ^4.20.3
  ts-node: ^10.9.2
  vite-plugin-environment: ^1.1.3
  vite-plugin-eslint: ^1.8.1
  vite-tsconfig-paths: ^5.1.4
  rollup-plugin-inject-process-env: ^1.3.1
  cross-env: ^10.0.0

  # NX
  '@nrwl/devkit': 19.8.4
  '@nrwl/js': ^19.8.4
  nx: 21.3.11

  # SWC
  '@swc-node/register': 1.10.10
  '@swc/core': 1.13.3
  '@swc/helpers': 0.5.17

  # Data fetching
  '@tanstack/react-query': ^5.84.1
  '@tanstack/react-query-devtools': ^5.84.1
  '@tanstack/react-virtual': ^3.13.12
  odata-query: ^8.0.3

  # Microsoft
  '@microsoft/applicationinsights-web': 3.3.9
  '@microsoft/applicationinsights-core-js': ^3.3.9

  # Testing
  '@types/jest': 30.0.0
  vitest: ^3.2.4
  '@testing-library/jest-dom': ^6.6.4
  '@testing-library/react': ^16.3.0
  '@testing-library/react-hooks': ^8.0.1

  # Utilities
  luxon: ^3.7.1
  '@types/luxon': ^3.7.1
  sortablejs: ^1.15.6
  '@types/sortablejs': ^1.15.8
  zustand: ^5.0.6
  re-resizable: ^6.11.2
  markdown-to-jsx: ^7.7.12
  date-fns: ^4.1.0
  core-js: ^3.45.0
  rimraf: ^6.0.1
  rxjs: ^7.8.2
  '@types/html-escaper': ^3.0.4
  '@types/node': 24.2.0

  # Remirror (markdown editor)
  remirror: ^3.0.2
  '@remirror/pm': ^3.0.1
  '@remirror/react': ^3.0.2
  '@remirror/react-editors': ^2.0.2
  '@remirror/react-ui': ^1.0.0
  '@remirror/styles': ^3.0.0
  '@remirror/theme': ^3.0.0

  # 3D/Model Viewer
  '@cognite/reveal': 4.25.3
  '@cognite/sdk': 10.0.0
  '@equinor/echo-3d-viewer': ^0.0.4
  three: 0.178.0
  '@types/three': ~0.179.0
  throttle-typescript: ^1.1.0

  # Power BI
  powerbi-client: ^2.23.1
  powerbi-client-react: ^2.0.0

  # Eslint
  eslint-plugin-import: 2.32.0
  eslint-plugin-jsx-a11y: 6.10.2
  eslint-plugin-react: 7.37.5
  eslint-plugin-react-hooks: 5.2.0
  eslint-plugin-tsdoc: ^0.4.0

  # Astro (docs)
  '@astrojs/react': 4.3.0
  astro: 5.12.4

  # GitHub Action
  '@actions/core': ^1.11.1
  '@actions/github': ^6.0.1
  adm-zip: ^0.5.16
  commander: 14.0.0
  markdown-table: 3.0.4
