export type WorkOrderCutoff = {
  sourceName: string | null;
  sourceIdentity: string;
  facility: string;
  project: string;
  cutoffWeek: string;
  cutoffDate: string;
  expendedManHoursLastWeek: number;
  earnedManHoursLastWeek: number;
  workOrderNo: string;
  title: string | null;
  description: string | null;
  plannedStartupDate: string;
  actualStartupDate: string | null;
  plannedCompletionDate: string;
  actualCompletionDate: string | null;
  commissioningPackageNo: string | null;
  milestone: string;
  category: string | null;
  holdBy: string | null;
  typeOfWork: string | null;
  onshoreOffshore: string | null;
  projectProgress: number;
  workOrderType: string | null;
  jobStatus: string;
  materialStatus: string;
  estimatedManHours: number;
  expendedManHours: number;
  remainingManHours: string | null;
  earnedManHours: number;
  subMilestone: string | null;
  responsible: string;
  discipline: string;
  location: string | null;
  updatedDate: string;
  workOrderId: string;
  constructionComments: string | null;
  materialComments: string | null;
  commissioningPackageId: string | null;
};
