name: Setup pnpm
description: Configures pnpm with cache and install deps

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: pnpm setup
      uses: ./.github/actions/reusable/pnpm-setup
      with:
        node-version: 18
        pnpm-version: 8.0.0
