export type Punch = {
  facility: string | null;
  punchItemNo: string;
  description: string | null;
  punchItemCategory: string | null;
  raisedByOrganization: string | null;
  clearingByOrganization: string | null;
  dueDate: string | null;
  punchPriority: string | null;
  punchListType: string | null;
  punchListSorting: string | null;
  estimate: string | null;
  workOrderNo: string | null;
  workOrderId: string | null;
  materialRequired: boolean | null;
  materialEstimatedTimeOfArrival: string | null;
  externalMaterialNo: string | null;
  clearedAtDate: string | null;
  rejectedAtDate: string | null;
  verifiedAtDate: string | null;
  updatedDate: string | null;
  responsible: string | null;
  formularType: string | null;
  tagNo: string | null;
  tagId: string | null;
  callOffNo: string | null;
  mechanicalCompletionPackageNo: string | null;
  mechanicalCompletionPackageId: string | null;
  commissioningPackageNo: string | null;
  commissioningPackageId: string | null;
  functionalSystem: string | null;
  c01PlannedDate: string | null;
  c01ForecastDate: string | null;
  c07PlannedDate: string | null;
  c07ForecastDate: string | null;
  priority1: string | null;
};
