name: Get fusion token
description: Gets a fusion token using the env vars

outputs:
  token:
    description: "Fusion <env> token"
    value: ${{ steps.token.outputs.token }}

runs:
  using: composite
  steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Get fusion token
      id: token
      uses: ./.github/actions/reusable/get-fusion-token
      secrets: inherit
      with:
        client-id: ${{ vars.SP_CLIENT_ID }}
        tenant-id: ${{ vars.TENANT_ID }}
        resource-id: ${{ vars.FUSION_CLIENT_ID }}
