import {
  MenuModule,
  ColumnsToolPanelModule,
  ServerSideRowModelModule,
  RowStyleModule,
  RowApiModule,
  ColumnApiModule,
  ColumnAutoSizeModule,
  TooltipModule,
  TextFilterModule,
  NumberFilterModule,
  DateFilterModule,
  SetFilterModule,
  MultiFilterModule,
  GroupFilterModule,
  CustomFilterModule,
  QuickFilterModule,
  ExternalFilterModule,
  AdvancedFilterModule,
  ClientSideRowModelModule,
} from '@equinor/workspace-fusion/grid';

export const defaultModules: any[] = [
  MenuModule,
  ColumnsToolPanelModule,
  ServerSideRowModelModule,
  RowStyleModule,
  RowApiModule,
  ColumnApiModule,
  ColumnAutoSizeModule,
  TooltipModule,
  TextFilterModule,
  NumberFilterModule,
  DateFilterModule,
  SetFilterModule,
  MultiFilterModule,
  GroupFilterModule,
  CustomFilterModule,
  QuickFilterModule,
  ExternalFilterModule,
  AdvancedFilterModule,
  ClientSideRowModelModule,
];
