export type PackageStatus =
  | 'PA'
  | 'PB'
  | 'RFOC Accepted'
  | 'RFOC Sent'
  | 'RFOC Rejected'
  | 'TAC Accepted'
  | 'TAC Sent'
  | 'TAC Rejected'
  | 'RFCC Rejected'
  | 'RFCC Accepted'
  | 'RFCC Sent'
  | 'DCC Accepted'
  | 'DCC Sent'
  | 'RFRC Accepted'
  | 'RFRC Sent'
  | 'OS'
  | 'No status'
  | 'OK';
