import { McStatus } from './mcStatuses';

export type McPackage = {
  projectIdentifier: string;
  // projectDescription: string;
  mechanicalCompletionPackageId: string;
  mechanicalCompletionPackageNo: string;
  mechanicalCompletionPackageUrlId: string;
  commissioningPackageId: string;
  commissioningPackageNo: string;
  commissioningPackageUrlId: string;
  commissioningPackageStatus: McStatus;
  description: string;
  remark: string;
  system: string;
  subsystem: string;
  location: string;
  disciplineDescription: string;
  // disciplineDescription: string;
  mechanicalCompletionStatus: McStatus;
  tagVolume: string;
  priority: string;
  // priorityDescription: string;
  priority2: string;
  // priority2Description: string;
  priority3: string;
  // priority3Description: string;
  phase: string;
  responsible: string;
  finalPunchPlannedDate: string;
  finalPunchForecastDate: string;
  finalPunchActualDate: string;
  punchAcceptActualDate: string;
  rfccPlannedDate: string;
  rfccForecastDate: string;
  rfccActualDate: string;
  tacPlannedDate: string;
  tacForecastDate: string;
  rfocPlannedDate: string;
  rfocForecastDate: string;
  rfocActualDate: string;
  tacIsShipped: boolean;
  tacIsAccepted: boolean;
  rfocIsShipped: boolean;
  rfocIsAccepted: boolean;
  rfocIsRejected?: boolean;
  rfccIsShipped: boolean;
  rfccIsAccepted: boolean;
  rfccIsRejected?: boolean;
  rfccShippedDate: string;
};
