export type PackageStatus =
  | 'PA'
  | 'PB'
  | 'RFO Accepted'
  | 'RFC Partly sent'
  | 'RFO Partly signed'
  | 'RFO Sent'
  | 'RFO Rejected'
  | 'RFO Partly signed'
  | 'TAC Accepted'
  | 'TAC Sent'
  | 'TAC Rejected'
  | 'RFC Rejected'
  | 'RFC Accepted'
  | 'RFC Partly signed'
  | 'RFC Sent'
  | 'DCC Accepted'
  | 'DCC Sent'
  | 'RFR Accepted'
  | 'RFR Sent'
  | 'OS'
  | 'No status'
  | 'OK';
