export type HeatTraceChecklist = {
  heatTraceCableNo: string;
  heatTraceCableId: string;
  heatTraceCableIdUrlId: string;
  facility: string;
  project: string;
  projectDescription: string;
  projectSchema: string;
  checklistId: string;
  checklistUrlId: string;
  formResponsible: string;
  mcResponsible: string;
  commResponsible: string;
  formularType: string;
  formularGroup: string;
  status: string;
  revision: string;
  signedDate: string;
  pipeTest: string;
  tagArea: string;
  mechanicalCompletionArea: string;
  mcDescription: string;
  mechanicalCompletionPackageNo: string;
  mechanicalCompletionPackageId: string;
  mechanicalCompletionPackageUrlId: string;
  mechanicalCompletionStatus: string;
  priority1: string;
  priority2: string;
  priority3: string;
  rfC_Planned_Forecast_Date: string;
  rfO_Planned_Forecast_Date: string;
  commissioningPackageNo: string;
  commissioningPackageId: string;
  commissioningPackageUrlId: string;
  system: string;
  checklistStep: string;
  checklistStepSequence: string;
  pipetestType: string;
  circuit: string;
  switchboard: string;
  tagNo: string;
  tagId: string;
  tagUrlId: string;
  tagDescription: string;
  heatTraceCableUrl: string | null;
  checklistUrl: string | null;
  commissioningPackageUrl: string | null;
  mechanicalCompletionUrl: string | null;
};
