export type MccrBase = {
  commissioningPackageId: string | null;
  commissioningPackageUrl: string | null;
  commissioningPackageUrlId: string | null;
  commpkgId: string | null;
  commpkgNumber: string | null;
  description: string | null;
  facility: string | null;
  mcPkgId: string | null;
  mccrId: string | null;
  mccrResponsible: string | null;
  mccrStatus: string | null;
  mccrType: string | null;
  mccrUrlId: string | null;
  mcpkgNumber: string | null;
  mechanicalCompletionPackageUrl: string | null;
  mechanicalCompletionPackageUrlId: string | null;
  project: string | null;
  tagId: string | null;
  tagNumber: string | null;
  tagUrl: string | null;
  tagUrlId: string | null;
  workOrderId: string | null;
  workOrderUrl: string | null;
  workOrderUrlId: string | null;
};
