export type SoftwareChangeRecord = {
  isOpen: boolean;
  node: string;
  functionalSystem: string;
  updatedDate: string;
  controlSystem: string;
  estimatedManHours: number;
  latestSignedRanking: number;
  latestSignedRole: string;
  nextToSign: string | null;
  nextToSignRanking: string | null;
  commissioningPackageId: string;
  commissioningPackageNo: string;
  modificationDescription: string;
  dueDate: string;
  closedDate: string;
  createdDate: string;
  softwareChangeRecordId: string;
  softwareChangeRecordUrl: string;
  softwareChangeRecordUrlId: string;
  softwareChangeRecordNo: string;
  commissioningPhase: string;
  status: string;
  supplier: string | null;
  title: string | null;
  priority: string;
  contract: string;
  projectDescription: string;
  action: string | null;
  project: string;
  projectSchema: string;
  description: string;
  facility: string;
};
