import { SwcrStatus } from './swcrStatus';

export type SwcrPackage = {
  swcrUrl: string;
  commissioningPackageUrl: string;
  softwareChangeRecordId: string;
  softwareChangeRecordUrlId: string;
  facility: string;
  createdDate: string;
  updatedDate: string;
  functionalSystem: string;
  nodeIdentifier: string;
  softwareChangeRecordNo: string;
  project: string;
  description: string;
  projectDescription: string;
  modificationDescription: string;
  priority: string;
  contract: string;
  supplier: string;
  dueDate: string;
  estimatedManHours: number;
  title: string;
  action: string;
  status: SwcrStatus;
  famUpsertedTime: string;
  nextToSignRole: string;
  nextToSignFunctionalRole: string;
  nextToSignRanking: number;
  latestSignedRanking: number;
  latestSignedRole: string;
  latestSignedRoleFunctionalRole: string;
  closedDate: string;
  isOpen: boolean;
  commissioningPackageNo: string;
  commissioningPackageId: string;
  commissioningPhase: string;
  projectSchema: string;
  commissioningPackageUrlId: string;
  rfOPlannedDate: string;
  rfOForecastDate: string;
  rfCPlannedDate: string;
  rfCForecastDate: string;
  system: string;
  automationControlSystem: string;
  swcrTypes: string
  commissioningPackageArea: string;
};
