import { BaseStatus } from '@cc-components/shared/types';

//TODO: Update to new properties when FAM is ready
export type HandoverPackage = {
  location: string | null;
  commissioningPackageNo: string;
  commissioningPackageId: string;
  commissioningPackageUrlId: string;
  commissioningPackageStatus: BaseStatus;
  description: string | null;
  dccShippedDate: string | null;
  rfrcActualDate: string | null;
  dccActualDate: string | null;
  rfrcForecastDate: string | null;
  rfrcPlannedDate: string | null;
  dccForecastDate: string | null;
  dccPlannedDate: string | null;
  rfrcShippedDate: string | null;
  rfcForecastDate: string | null;
  rfcPlannedDate: string | null;
  rfcShippedDate: string | null;
  rfoForecastDate: string | null;
  rfoPlannedDate: string | null;
  rfoActualDate: string | null;
  tacForecastDate: string | null;
  tacPlannedDate: string | null;
  isDemolition: boolean;
  mechanicalCompletionPkgsCount: number;
  mechanicalCompletionPkgsRfccShippedCount: number;
  mechanicalCompletionPkgsRfccSignedCount: number;
  mechanicalCompletionPkgsRfocShippedCount: number;
  mechanicalCompletionPkgsRfocSignedCount: number;
  mechanicalCompletionStatus: BaseStatus;
  phase: string | null;
  priority1: string | null;
  priority2: string | null;
  priority3: string | null;
  progress: number | null;
  projectIdentifier: string | null;
  projectDescription: string | null;
  remark: string | null;
  responsible: string | null;
  isRfcAccepted: boolean;
  isRfcShipped: boolean;
  isRfcRejected: boolean;
  isRfoAccepted: boolean;
  isRfoShipped: boolean;
  isRfoRejected: boolean;
  isTacAccepted: boolean;
  isTacShipped: boolean;
  isTacRejected: boolean;
  system: string | null;
  subSystem: string | null;
  volume: number;
  hasUnsignedActions: boolean;
};
