name: Post PRs to Teams

on:
  pull_request:
    types: [opened, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: 'Deploy affected apps to Fusion CI'
        shell: bash
        run: echo "PACKAGES=$(turbo run build --filter='./apps/*'[origin/main] --dry-run=json | jq '.packages')" >> $GITHUB_ENV

      - name: Comment pr
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Deployed! 🚀 Packages: ${{ toJson(github.env.PACKAGES) }}'
            })
