name: Update issue

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 7 * * *'
permissions:
  issues: write
  id-token: write
jobs:
  update-issue:
    name: Update issue
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to fetch range

      - name: PNPM setup
        uses: ./.github/actions/pnpm-setup

      - name: Get fusion token
        id: 'get-fusion-token-ci'
        uses: ./.github/actions/get-fusion-token
        with:
          client-id: ${{secrets.AZURE_CLIENT_ID}}
          tenant-id: ${{secrets.AZURE_TENANT_ID}}
          resource-id: ${{secrets.AZURE_RESOURCE_ID}}

      - name: Get fusion token
        id: 'get-fusion-token-fprd'
        uses: ./.github/actions/get-fusion-token
        with:
          client-id: ${{secrets.AZURE_PROD_CLIENT_ID}}
          tenant-id: ${{secrets.AZURE_TENANT_ID}}
          resource-id: ${{secrets.AZURE_RESOURCE_PROD_ID}}

      - name: 'Update issue'
        shell: bash
        run: npx tsx ./github-action/src/issue.ts issue -T ${{ github.token }} -C ${{steps.get-fusion-token-ci.outputs.token}} -F ${{steps.get-fusion-token-fprd.outputs.token}}
