name: 👮Verify linked issue

# This action works with pull requests and pushes
permissions:
  {
    contents: read,
    actions: read,
    checks: read,
    deployments: read,
    discussions: read,
    id-token: write,
    issues: write,
    packages: read,
    pages: read,
    pull-requests: write,
    repository-projects: read,
    security-events: read,
    statuses: read,
  }
on:
  pull_request:

jobs:
  update-issue:
    name: Update issue
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check issue👮
        uses: Gustav-Eikaas/issue-checker@v0.0.3
        with:
          pr-number: ${{github.event.number}}
