name: Update issue

on:
  push:
    branches: ['main']
  pull_request:
    types: [opened, synchronize]

jobs:
  update-issue:
    name: Update issue
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to fetch range

      - name: Install Dependencies
        run: npm i -g pnpm typescript && pnpm i

      - name: 'Update issue'
        shell: bash
        run: npx ts-node --esm ./github-action/src/issue.ts issue -T ${{ github.token }}
