name: Manual deploy fusion app TEST

on:
  workflow_dispatch:
    inputs:
      appKey:
        type: string
        description: Which app to deploy to test
permissions: write-all
jobs:
  deploy-manual-ci:
    runs-on: ubuntu-latest
    environment: ci
    steps:
      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          allow-no-subscriptions: true

      - name: 'Obtain token for upload'
        shell: bash
        run: echo "FUSION_TOKEN=$(az account get-access-token --resource '${{ secrets.AZURE_RESOURCE_ID }}' | jq '.accessToken')" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to fetch range

      - name: Install Dependencies
        run: npm i -g pnpm typescript && pnpm i

      - name: Build monorepo
        run: npx turbo run build --filter=${{inputs.appKey}}

      - name: 'Deploy affected apps to Fusion CI env'
        shell: bash
        env:
          #Runs out of memory when bundling more apps otherwise even though concurrency is 1
          NODE_OPTIONS: '--max_old_space_size=4096'
        run: npx turbo run pr:deploy --filter=${{inputs.appKey}} --concurrency 1 -- --token ${{ env.FUSION_TOKEN }}
