name: Manual deploy fusion app TEST🚀

on:
  workflow_dispatch:
    inputs:
      appKey:
        type: string
        description: Which app to deploy to test
permissions:
  actions: read
  checks: write
  contents: read
  deployments: write
  id-token: write
  statuses: write
jobs:
  deploy-manual-ci:
    runs-on: ubuntu-latest
    environment: ci
    steps:
      - name: Get fusion token
        id: 'get-fusion-token'
        uses: ./.github/actions/get-fusion-token
        with:
          client-id: ${{secrets.AZURE_CLIENT_ID}}
          tenant-id: ${{secrets.AZURE_TENANT_ID}}
          resource-id: ${{secrets.AZURE_RESOURCE_ID}}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to fetch range

      - name: PNPM setup
        uses: ./.github/actions/pnpm-setup

      - name: Build monorepo
        run: npx turbo run build --filter='${{inputs.appKey}}'

      - name: 'Deploy affected apps to Fusion CI env'
        shell: bash
        env:
          #Runs out of memory when bundling more apps otherwise even though concurrency is 1
          NODE_OPTIONS: '--max_old_space_size=4096'
        run: npx turbo run pr:deploy --filter='${{inputs.appKey}}' --concurrency 1 -- --token ${{ steps.get-fusion-token.outputs.token }}
