name: Onboard app to Fusion Project Portal
# run-name: ${{github.actor}} is onboarding ${{inputs.appKey}} to ${{inputs.contexId}}
#
on:
  pull_request:
#   workflow_dispatch:
#     inputs:
#       appKey:
#         type: string
#         description: Which app to onboard
#       contextId:
#         type: string
#         description: Which contextId to onboard the app on
#       env:
#         type: choice
#         description: Which environment to use
#         options:
#           - ci
#           - fprd

permissions:
  actions: read
  contents: read
  deployments: write
  id-token: write
  statuses: write

jobs:
  onboard-app:
    runs-on: ubuntu-latest
    environment: ci
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get fusion token
        id: "get-fusion-token"
        uses: ./.github/actions/get-fusion-token
        with:
          client-id: ${{vars.FUSION_CLIENT_ID}}
          resource-id: ${{vars.SP_CLIENT_ID}}
          tenant-id: ${{vars.TENANT_ID}}

      - name: PNPM setup
        uses: ./.github/actions/pnpm-setup

      - name: Onboard app
        shell: bash
        run: npx tsx ./github-action/src/onboardApp.ts onboard --token ${{steps.get-fusion-token.outputs.token}} --appkey handover --env ci --context 07135497-aa7b-4a5e-b229-cdc326ddcaec
