name: PR-Bot

on: pull_request

jobs:
  build:
    name: Build
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: read file
        run: echo "MESSAGE=$(cat ./github/workflows/pr-bot.txt)" >> $GITHUB_ENV

      - name: Comment pr
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Beep boop i'm the PR bot🤖 \r\n Available commands are: \r\n Deploy Test \r\n Create fusion app'
            })
