name: PR-Bot

on: pull_request

jobs:
  build:
    name: Build
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to fetch range

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'

      - name: Install Dependencies
        run: npm i -g typescript && pnpm install

      - name: Comment info pr
        shell: bash
        run: npx ts-node --esm ./github-action/src/pull-request-bot/pull-request-bot.ts info -T ${{ secrets.GITHUB_TOKEN }}
