name: PR-Bot

on: pull_request

jobs:
  build:
    name: Build
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - uses: xt0rted/pull-request-comment-branch@v2
        id: comment-branch

      - name: Build monorepo
        run: echo "MESSAGE=$(cat ./github/workflows/pr-bot.txt)" >> $GITHUB_ENV

      - name: Comment pr
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ${{env.MESSAGE}}
            })
