name: 'Deploy PR build'
on:
  pull_request:
    types: [labeled]

permissions:
  actions: read
  issues: write
  checks: write
  contents: read
  pull-requests: write
  deployments: write
  id-token: write
  statuses: write

jobs:
  deploy-affected-ci:
    if: github.event.label.name == 'deploy-test'
    runs-on: ubuntu-latest
    environment: ci
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          persist-credentials: false

      - name: Get fusion token
        id: 'get-fusion-token'
        uses: ./.github/actions/get-fusion-token
        with:
          client-id: ${{secrets.AZURE_CLIENT_ID}}
          tenant-id: ${{secrets.AZURE_TENANT_ID}}
          resource-id: ${{secrets.AZURE_RESOURCE_ID}}

      - name: PNPM setup
        uses: ./.github/actions/pnpm-setup

      - name: Build monorepo
        run: pnpm ci:build

      - name: 'Deploy affected apps to Fusion CI'
        shell: bash
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
          GITHUB_STEP_SUMMARY: $GITHUB_STEP_SUMMARY
        run: npx turbo run pr:deploy --since origin/main --scope * --concurrency 1 -- --token ${{ steps.get-fusion-token.outputs.token }} --pr '${{ github.event.pull_request.number }}' --ai '${{secrets.ai}}' --modelViewerConfig '${{vars.modelViewerConfig}}' --sha '${{ github.event.pull_request.head.sha }}'

      - name: Comment PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Deployed! 🚀'
            })

      - name: Remove deploy label
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            try {
              await github.rest.issues.removeLabel({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: 'deploy-test'
              });
            } catch (e) {
              core.info('Label already removed or not found');
            }
