name: PNPM-PR-Snyk-Check

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:

jobs:
  pnpm_snyk_check:
    runs-on: ubuntu-latest
    name: Snyk post processing
    steps:
      - uses: actions/checkout@v2
      - name: pnpm Snyk Delta
        id: pnpm-snyk-delta
        uses: snyk-tech-services/github-actions-pnpm-snyk@master
        with:
          snykToken: ${{ secrets.SNYK_TOKEN }}
          snykOrganization: Fusion Project Portal
          pnpmLockfilePath: './pnpm-lock.yaml'
          # snykArguments: "--severity-threshold=high"
          # breakBuild: false
          # fullScan: false
