name: Sync admins

on:
  pull_request:

permissions:
  actions: read
  checks: write
  contents: read
  deployments: write
  id-token: write
  statuses: write
jobs:
  sync-admins-ci:
    runs-on: ubuntu-latest
    environment: ci
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to fetch range

      - name: Get fusion token
        id: "get-fusion-token-ci"
        uses: ./.github/actions/get-fusion-token
        with:
          client-id: ${{secrets.AZURE_CLIENT_ID}}
          tenant-id: ${{secrets.AZURE_TENANT_ID}}
          resource-id: ${{secrets.AZURE_RESOURCE_ID}}

      - name: PNPM setup
        uses: ./.github/actions/pnpm-setup

      - name: "Sync admins Fusion CI"
        shell: bash
        run: npx tsx ./github-action/src/sync-admins.ts sync -T ${{ steps.get-fusion-token-ci.outputs.token }} -G 'Lighthouse FAM Self Service Contributor' --spid '5e4cc9f6-122d-4434-a4cd-46c808507458' -E 'CI'
