name: 'build-test'
on: # rebuild any PRs and main branch changes
  push:

jobs:
  changed: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required to fetch range

      - name: Install Dependencies
        run: npx pnpm i

      # Run the action on the yarn-workspaces example
      - name: Test Action
        id: changedAction
        uses: ./
        with:
          turbo-command: build
